### ISSUE TITLE
no urls create

### ISSUE THREAD

**Issue by azadpsg** [MortezaBashsiz/CFAnsible#11]
Dear Maintainers

I've done all config as explained in video and ansible logs would go all right and at last I have no failed tasks, but  "v2ray : generate vmess url" would not create urls for me. I've tried to run v2ray.sh with variables by myself or taged the task and rerun it but still it would result with OK but no urls in the /opt/v2ray_urls path.

please help me with this issue

**Comment by MortezaBashsiz** [comment]
Hi
Please run the Ansible again
It has some changes
