### ISSUE TITLE
Failed to connect to  the host via ssh - shh keys are set.

### ISSUE THREAD

**Issue by pouyaGit** [MortezaBashsiz/CFAnsible#12]
I can shh without password but when I run paly I get this(running debian 11):

root@v79953906:~/CFAnsible# ansible-playbook plays/v2ray.yml

[WARNING]: Unhandled error in Python interpreter discovery for host 1.1.1.1: Failed to connect to

the host via ssh: root@1.1.1.1: Permission denied (publickey,password).

fatal: [1.1.1.1]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"1.1.1.1\". Make sure this host can be reached over ssh: [Errno 32] Broken pipe", "unreachable": true}

PLAY RECAP *********************************************************************************************

1.1.1.1                 : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by saeidskyboy** [comment]
did you change your inventory.yml ?
you are suppose to replace your sever's IP to those pre set IPs (which is 1.1.1. or 2.2.2)
one more thing, it's possible your .ssh configuration file is restricted (i.e no one can ssh as root which you can change it.
watch out 8:12 of https://www.youtube.com/watch?v=Qp6oI_xd4B0&t=882s

**Comment by MortezaBashsiz** [comment]
You need to resolve it by yourself

**Comment by esmaily** [comment]
Hi guys 
I'm have same error in some of servers but another servers is ok

[WARNING]: Unhandled error in Python interpreter discovery for host X.X.X.X: Failed to connect to the host via ssh: root@91.107.179.198: Permission
denied (publickey,password).
fatal: [X.X.X.X]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"X.X.X.X\". Make sure this host can be reached over ssh: root@X.X.X.X: Permission denied (publickey,password).\r\n", "unreachable": true}

**Comment by esmaily** [comment]
But after add this option it's solved 

`ansible-playbook  plays/v2ray.yml --ask-pass`
