### ISSUE TITLE
Disable SSH

### ISSUE THREAD

**Issue by barzin144** [MortezaBashsiz/CFAnsible#13]
Hi, Morteza
Thank you for helping Iranian people to able to connect to internet
Already when our server's IP is blocked we cannot connect to it via SSH, but it's possible to connect to server via server panel like (https://console.hetzner.cloud/)
If you can please disable SSH and change your code (in another branch) to run everything inside the server, with this feature we can clone your code inside our server and run it.

Thank you

**Comment by MortezaBashsiz** [comment]
Hi
You already can run ansible from inside of the VM to configure itself
Use your VM as client
