### ISSUE TITLE
ansible-playbook plays/v2ray.yml ارور میده

### ISSUE THREAD

**Issue by TiamaaShah** [MortezaBashsiz/CFAnsible#6]
ansible-playbook plays/v2ray.yml
وقتی کامند بالا رو اجرا میکنم بعد از 6 تا اوکی ارور میده
TASK [sysctl : apply sysctl]
fatal: [****.****.****.***]: FAILED! => {"changed": true, "cmd": "sysctl -p /etc/sysctl.d/99-sysctl.conf\n", "delta": "0:00:00.010555", "end": "2023-03-04 07:39:57.077003", "msg": "non-zero return code", "rc": 255, "start": "2023-03-04 07:39:57.066448", "stderr": "sysctl: cannot stat /proc/sys/net/core/netdev_max_backlog: No such file or directory\nsysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory\nsysctl: cannot stat /proc/sys/net/core/wmem_max: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv4/tcp_congestion_control: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv4/tcp_fin_timeout: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv4/tcp_limit_output_bytes: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv4/tcp_low_latency: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv4/tcp_max_tw_buckets: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv4/tcp_rmem: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_reuse: No such file or directory\nsysctl: cannot stat /proc/sys/net/ipv4/tcp_wmem: No such file or directory", "stderr_lines": ["sysctl: cannot stat /proc/sys/net/core/netdev_max_backlog: No such file or directory", "sysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory", "sysctl: cannot stat /proc/sys/net/core/wmem_max: No such file or directory", "sysctl: cannot stat /proc/sys/net/ipv4/tcp_congestion_control: No such file or directory", "sysctl: cannot stat /proc/sys/net/ipv4/tcp_fin_timeout: No such file or directory", "sysctl: cannot stat /proc/sys/net/ipv4/tcp_limit_output_bytes: No such file or directory", "sysctl: cannot stat /proc/sys/net/ipv4/tcp_low_latency: No such file or directory", "sysctl: cannot stat /proc/sys/net/ipv4/tcp_max_tw_buckets: No such file or directory", "sysctl: cannot stat /proc/sys/net/ipv4/tcp_rmem: No such file or directory", "sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_reuse: No such file or directory", "sysctl: cannot stat /proc/sys/net/ipv4/tcp_wmem: No such file or directory"], "stdout": "net.ipv4.ip_forward = 0\nkernel.randomize_va_space = 0", "stdout_lines": ["net.ipv4.ip_forward = 0", "kernel.randomize_va_space = 0"]}

البته من توی متن جای آی پی ستاره گذاشتم اینجا .

**Comment by MortezaBashsiz** [comment]
درود
سیستم عامل چه توزیعی از لینوکس هست؟
`uname -a`

**Comment by TiamaaShah** [comment]
درود

Server : Debian 11 64bit
Linux **.**.** 4.19.0 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 GNU/Linux
=========================================================
Client (My PC): Ubuntu 22
Linux **-**-** 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MortezaBashsiz** [comment]
این مشکل عجیبه
شاید از یه دبیان کاستومایز شده استفاده میکنید
و نمیتونم توی این زمینه کمکی بکنم
چون مشکل اینه که نمیتونه پارامترای کرنل رو پیدا کنه
