### ISSUE TITLE
nginx error

### ISSUE THREAD

**Issue by hossein-a-z** [MortezaBashsiz/CFAnsible#8]
سلام
من طبق مراحل پیش رفتم ولی توی nginx ارور میده

`RUNNING HANDLER [nginx : reload nginx] *********************************************************************************
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "msg": "Unable to start service nginx: Job for nginx.service failed because the control process exited with error code.\nSee \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}`

توی خود سرور این پیامو میده

`Mar 05 23:54:00 debian-gb1 systemd[1]: Starting A high performance web server and a reverse proxy server...
Mar 05 23:54:00 debian-gb1 nginx[10050]: nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/debian-domain.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/debian-domain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
Mar 05 23:54:00 debian-gb1 nginx[10050]: nginx: configuration file /etc/nginx/nginx.conf test failed
Mar 05 23:54:00 debian-gb1 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Mar 05 23:54:00 debian-gb1 systemd[1]: nginx.service: Failed with result 'exit-code'.
Mar 05 23:54:00 debian-gb1 systemd[1]: Failed to start A high performance web server and a reverse proxy server.`

**Comment by MortezaBashsiz** [comment]
درود
شما واقعا دومین
debian-domain.com
رو دارید؟
اگه دارید چرا پس هاستنیم رو ست نکردید توی کانفیگ
دقت کنید که همه مراحل رو درست رفته باشید
مشخصا مغایرتی بین هاستنیم و دومینتون وجود داره و اون مقداری که توی کانفیگ اسنیبل میزنید
