### ISSUE TITLE
v2ray are generated, but but working

### ISSUE THREAD

**Issue by mohammadmahdizeynali** [MortezaBashsiz/CFAnsible#9]
hi, tnx for your help
I complete the steps of running ansible, it reaches the end without any error; v2ray links are also generated, but it doesn't work inside v2ray clients, I even replaced Cloudflare's ip, but still the connection is failed!

**Comment by MortezaBashsiz** [comment]
It seems your cloudflare configuration is not correct
Make sure you are full https in your cloudflare panel
